# Generated by Django 5.0.6 on 2024-07-05 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsnih', '0002_alter_accountuser_account_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('7eb22ca4-526f-4609-96d1-2a26c772f589'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('85251dd3-8c3f-4096-b4c8-d6dd3ea67928'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
